/**
 * Configuration Forms UI.
 *
 * <p>
 * Provides a generic Vaadin-based UI for editing configuration beans
 * defined in {@code config-core}.
 * </p>
 *
 * <p>
 * Forms are generated by convention:
 * Java type + Bean Validation + optional metadata annotations.
 * </p>
 *
 * <p>
 * This module depends on {@code ui-kit} and contains no domain logic.
 * </p>
 */
package de.javaholic.toolkit.config.ui;
